In [16]:
#we use logistic regression example
import torch

In [17]:
import torch.nn.functional as F

In [23]:

y = torch.tensor([1.0]) #true label
x1 = torch.tensor([1.1]) #input feature
w1 = torch.tensor([2.2], requires_grad=True) #weight parameter
b  = torch.tensor([0.0], requires_grad=True)
z = x1*w1 + b  # output
activation_function_out_put = torch.sigmoid(z) #output going through activation function aka sigmoid

In [24]:
loss = F.binary_cross_entropy(activation_function_out_put, y)
loss

tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)

In [25]:
# in the above code, we just calculated the the loss of a forward pass of a single layer neuron or 
# applied logistic regression forward pass!

In [26]:
# compute gradients via autogram
from torch.autograd import grad

In [27]:
grad_loss_w1 = grad(loss, w1, retain_graph = True )
grad_loss_w1

(tensor([-0.0898]),)

In [28]:
grad_loss_b = grad(loss, b, retain_graph = True )
grad_loss_b

(tensor([-0.0817]),)

In [29]:
# in the above 2 cells, we were using manual gradient calculation
# we can use backward function to find out gradients for all the leaf nodes of the graph
loss.backward()

In [30]:
w1.grad

tensor([-0.0898])

In [31]:
b.grad

tensor([-0.0817])