In [1]:
import torch

In [48]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()
        self.layers = torch.nn.Sequential(
        
            #1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),
            
            #2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),
            
            #output layer
            torch.nn.Linear(20, num_outputs)
        )
    def forward(self, x):
        logits = self.layers(x)
        return logits          #outputs of the last layer are called logits
model = NeuralNetwork(50, 3)

In [49]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [50]:
# calculate the total number of trainable parameters of this model
def calculate_trainable_parameters_of_model(model):
    total = 0
    for parameter in model.parameters():
        if parameter.requires_grad:
            total += parameter.numel()
    return total

In [51]:
calculate_trainable_parameters_of_model(model)

2213

In [52]:
# a little shortcut way to calculate trainable parameters of model
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
num_params

2213

In [53]:
#check the first layers weight parameters
print(model.layers[0].weight)


#check its size too
print(model.layers[0].weight.shape)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)
torch.Size([30, 50])


In [54]:
# check the bias of first layer and its size
print(model.layers[0].bias)

print(model.layers[0].bias.shape)

Parameter containing:
tensor([-0.1250,  0.0513,  0.0366,  0.0075,  0.0509,  0.0545, -0.0393,  0.0924,
        -0.1412, -0.1232, -0.1063,  0.0081, -0.1249,  0.0101, -0.0019, -0.1298,
         0.1388, -0.0330,  0.1017,  0.1247, -0.0554, -0.0417,  0.1388,  0.0159,
         0.1215,  0.0385,  0.0769, -0.1224, -0.0279,  0.0991],
       requires_grad=True)
torch.Size([30])


In [55]:
#using manual seed to get the same initialized weights of nn model
torch.manual_seed(123)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [59]:
X = torch.rand((1, 50)) # generating random 50 features for the initial input values of the created neural network model above
print(X)

tensor([[0.5432, 0.2185, 0.3834, 0.3720, 0.5374, 0.9551, 0.7475, 0.4979, 0.8549,
         0.2438, 0.7577, 0.4536, 0.4130, 0.5585, 0.1170, 0.5578, 0.6681, 0.9275,
         0.3443, 0.6800, 0.9998, 0.2855, 0.9753, 0.2518, 0.7204, 0.6959, 0.6397,
         0.8954, 0.2979, 0.6314, 0.5028, 0.1239, 0.3786, 0.1661, 0.7211, 0.5449,
         0.5490, 0.3483, 0.5024, 0.3445, 0.6437, 0.9856, 0.5757, 0.2785, 0.1946,
         0.5382, 0.1291, 0.1242, 0.1746, 0.3302]])


In [61]:
# now we get the output from the model
Y = model(X)  # basically calling the forward method of that created class
print(Y)

tensor([[-0.1224,  0.1124, -0.0906]], grad_fn=<AddmmBackward0>)


In [66]:
# here, the term Addmm refering that the final out_put is produced by addition_and_matrix_multiplication operation
# PyTorch will use the backward function AddmmBackward0 to compute gradients for the tensors involved in that operation.
# if we only want to infer the model then we don't need to keep track of gradients
# so, the previous cells inference can be done without keeping track of gradients
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1224,  0.1124, -0.0906]])


In [71]:
#in pytorch, it is a common practice to code models such that they return the outputs of the 
#last layer without passing them to a non linear activation function (checkout the reason on the internet)
#thats why
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)  # here dim refers to which dimension of output tensor its gonna apply softmax
print(out)    

tensor([[0.3033, 0.3836, 0.3131]])
