# Tinkering pytorch tensors

In [1]:
#Tensor is a data-container!

pip install torch

Defaulting to user installation because normal site-packages is not writeable
     -------------------------------------- 212.4/212.4 MB 1.1 MB/s eta 0:00:00
     ---------------------------------------- 6.3/6.3 MB 1.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [7]:
import torch

In [9]:
torch.__version__

'2.4.0+cpu'

In [10]:
torch.cuda.is_available() # cuda is kind of a helper that helps utilizing gpu when performing tensor operations

False

In [6]:
pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu118

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\HP\\AppData\\Roaming\\Python\\Python39\\site-packages\\~orch\\lib\\asmjit.dll'
Check the permissions.



Defaulting to user installation because normal site-packages is not writeable
     -------------------------------------- 198.0/198.0 MB 1.1 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.7.0
    Uninstalling torch-2.7.0:
      Successfully uninstalled torch-2.7.0
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://download.pytorch.org/whl/cu118
     ---------------------------------------- 5.0/5.0 MB 1.3 MB/s eta 0:00:00
     ---------------------------------------- 4.0/4.0 MB 1.5 MB/s eta 0:00:00
     ----                                     0.3/2.7 GB 1.3 MB/s eta 0:29:47
Note: you may need to restart the kernel to use updated packages.


ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch==2.4.0 from https://download.pytorch.org/whl/cu118/torch-2.4.0%2Bcu118-cp39-cp39-win_amd64.whl#sha256=0da13570771e09f6d754196aa865a690222d683df07b62f20922a3f27546faf5:
        Expected sha256 0da13570771e09f6d754196aa865a690222d683df07b62f20922a3f27546faf5
             Got        9d77d401c9c0cbff8e72acc6bd36e6535627e85e5063f0ee2260a87a1f613967



In [5]:
tensor1d = torch.tensor([1, 2, 3])

In [6]:
tensor1d.dtype

torch.int64

In [7]:
floatvec = tensor1d.to(torch.float32)

In [8]:
floatvec.dtype

torch.float32

In [6]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://download.pytorch.org/whl/cu126
  Using cached https://download.pytorch.org/whl/cu126/torchvision-0.22.0%2Bcu126-cp39-cp39-win_amd64.whl (6.3 MB)
  Using cached https://download.pytorch.org/whl/cu126/torchaudio-2.7.0%2Bcu126-cp39-cp39-win_amd64.whl (4.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [11]:
# basic operations that we perform while working with tensors

In [13]:
tensor2d = torch.tensor([[1, 2],[3, 4]])

In [14]:
tensor2d

tensor([[1, 2],
        [3, 4]])

In [16]:
#finding shape of a tensor
tensor2d.shape

torch.Size([2, 2])

In [25]:
#reshaping a particular tensor
reshaped_tensor_2d = tensor2d.view(1, 4)

In [26]:
tensor2d

tensor([[1, 2],
        [3, 4]])

In [28]:
# finding transpose(row->col, col->row) of a tensor
transpose_tensor_2d = tensor2d.T
transpose_tensor_2d

tensor([[1, 3],
        [2, 4]])

In [39]:
#create another 2d tensor
another_tensor2d = torch.tensor([[1, 2, 3, 4], [3, 4, 5, 6]])

In [40]:
transpose_another_tensor2d = another_tensor2d.T

In [41]:
transpose_another_tensor2d

tensor([[1, 3],
        [2, 4],
        [3, 5],
        [4, 6]])

In [42]:
#performing matrix multiplication of tensors
matmul_tensor = tensor2d_another.matmul(transpose_another_tensor2d)
matmul_tensor

tensor([[30, 50],
        [50, 86]])